config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

 resources :contacts, only: [:new, :create] do
  collection do
   post :confirm
  end
 end

 resources :topics do
  resources :comments
  post :confirm, on: :collection
  collection do
   post :confirm
  end
 end

 resources :poems, only:[:index, :show] do
 end

 resources :relationships, only: [:create, :destroy]

 resources :conversations do
  resources :messages
 end

 devise_for :users, controllers: {
   registrations: "users/registrations",
   omniauth_callbacks: "users/omniauth_callbacks"
 }

 resources :users, only: [:index, :show]

 if Rails.env.development?
   mount LetterOpenerWeb::Engine, at: "/letter_opener"
 end

 root 'top#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    validates :title, presence: true
    belongs_to :user


    has_many :comments, dependent: :destroy

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:edit, :update, :destroy, :show]

  def index
    @topics = Topic.all
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
      @topic = Topic.new
    end
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topics_path, notice: "トピックを作成しました！"
#      NoticeMailer.sendmail_topic(@topic).deliver
    else
      render 'new'
    end
  end

  def confirm
    @topic = Topic.new(topics_params)
    render :new if @topic.invalid?
  end

  def edit
  end

  def update
    @topic.update(topics_params)
    if @topic.save
      redirect_to topics_path, notice: "トピックを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice: "トピックを削除しました！"
  end

  private
    def topics_params
      params.require(:topic).permit(:title, :content)
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_topics_path
    elsif action_name == 'edit'
      topic_path
    end
  end

end

app/views/topics/_form.html.erb
<%= form_for(@topic, url: choose_new_or_edit) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= @topic.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :タイトル %>
  <%= f.text_field :title, class: 'form-control' %>
  <br>
  <%= f.label :内容 %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "トピック一覧画面にもどる", topics_path %>

app/views/topics/confirm.html.erb
<div class="container">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@topic) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <p>タイトル:<%= @topic.title %></p>
      <p>本文:<%= @topic.content %></p>
      <%= f.submit "登録する", class: 'btn btn-primary btn-block' %>
    <% end %>

    <%= form_for(@topic, url: new_topic_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>


  </div>
</div>

app/views/topics/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>トピックを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">

  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h3>トピック一覧</h3>
      <%= link_to "トピックを作成する", new_topic_path, class: 'btn btn-default' %>
    <% @topics.each do |topic| %>
    <div class="row">
      <%= link_to topic_path(topic)do %>
        <h4><strong><%= topic.title %></strong></h4>
      <% end %>
      <p><%= topic.content %></p>
      <p><%= topic.user.name %></p>
      <p><%= profile_img(topic.user) %></p>
      <%= link_to "編集", edit_topic_path(topic.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", topic_path(topic.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>

  <div id="page-blogtop-btn" class="page-blogtop-btn">
    <p><a class="move-page-blogtop" id="move-page-blogtop">▲</a></p>
  </div>

</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
      <h2>トピックを作成する</h2>
      <%= render 'form' %>
  </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="blog-text">
      <p class="left"><strong>タイトル</strong></p>
      <p class="left"><%= @topic.title %></p>
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @topic.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <% if current_user.id == @topic.user_id %>
      <%= link_to '編集', edit_topic_path(@topic) %> |
    <% end %>
    <%= link_to '戻る', topics_path %>
  </div>
</div>